###### INFORMATION ######
# TimeIsMoney Plugin
# Developed by: Soulz
# Discord: Soul ✞#9999


###### AUTO ######

# How much will online players gain per tick?
money-gain: 0.01 # Default = (0.01) || $1 per 100 ticks


###### BREAK ######

# How much will the player gain everytime a block is broken?
break-block-money-gain: 1 # Default - (1) || $1 per block mined
# Tip Message When Players Gain Money
break-block-tip: "§b$1 §7Gained from Mining"


###### PLACE ######

# How much will the player gain everytime a block is placed?
place-block-money-gain: 0.2 # Default - (0.2) || $1 per 5 blocks mined
# Tip Message When Players Gain Money
place-block-tip: "§b$0.2 §7Gained from Mining"


###### KILL ######

# How much will the killer recieve per kill?
kill-player-money-gain: 1000 # Default - (1000) || $1000 per player killed
# Tip Message When Players Gain Money
kill-player-message: "§b$1000 §7Recieved from §bKilling a Player!"


# Colours and Format Codes
#  §4  ==  Dark Red
#  §c  ==  Red
#  §6  ==  Gold
#  §e  ==  Yellow
#  §2  ==  Dark Green
#  §a  ==  Green
#  §b  ==  Aqua
#  §3  ==  Dark Aqua
#  §6  ==  Dark Blue
#  §9  ==  Blue
#  §d  ==  Light Purple
#  §5  ==  Dark Purple
#  §f  ==  White
#  §7  ==  Gray
#  §8  ==  Dark Gray
#  §0  ==  Black 

#  §k  ==  Obfuscated
#  §l  ==  Bold
#  §i  ==  Italic
#  §r  ==  Reset
